// vb6comserver.c - VB6 COM Server Runtime (P6.6 ActiveX DLL)
// Implements IClassFactory, IDispatch wrapper, DLL export skeleton, registry helpers

#include <string.h>
#include <wchar.h>   /* 账 #173 census: swprintf 的原型 (此前走 C4013) */
#define COBJMACROS  /* Enable C COM macros (ITypeLib_Release etc.) */
#include "vb6comserver.h"
#include "vb6comserver_internal.h"

#ifndef GUIDKIND_DEFAULT_SOURCE_DISP_IID
#define GUIDKIND_DEFAULT_SOURCE_DISP_IID 1
#endif

#ifndef CONNECT_E_NOCONNECTION
#define CONNECT_E_NOCONNECTION 0x80040200
#endif

// ANSI CLSID string -> GUID (MSVC doesn't export vb6_CLSIDFromStrA, manually convert to wide)
HRESULT vb6_CLSIDFromStrA(const char* str, CLSID* clsid) {
    wchar_t wbuf[64];
    MultiByteToWideChar(CP_ACP, 0, str, -1, wbuf, 64);
    return CLSIDFromString(wbuf, clsid);
}

// ============================================================
// Global reference counts
// ============================================================

LONG g_vb6_cRef = 0;
LONG g_vb6_cServerLock = 0;

// g_vb6_coclasses and g_vb6_coclassCount are generated by cgen in DLL mode
// Non-DLL mode: vb6comserver.c is not linked into EXE, no weak refs needed

// ============================================================
// IUnknown / IDispatch helper GUIDs
// ============================================================

const IID IID_IUnknown_ = {0x00000000,0x0000,0x0000,{0xC0,0x00,0x00,0x00,0x00,0x00,0x00,0x46}};
const IID IID_IDispatch_ = {0x00020400,0x0000,0x0000,{0xC0,0x00,0x00,0x00,0x00,0x00,0x00,0x46}};
const IID IID_IClassFactory_ = {0x00000001,0x0000,0x0000,{0xC0,0x00,0x00,0x00,0x00,0x00,0x00,0x46}};
const IID IID_IConnectionPointContainer_ = {0xB196B284,0xBAB4,0x101A,{0xB6,0x9C,0x00,0xAA,0x00,0x34,0x1D,0x07}};
const IID IID_IConnectionPoint_ = {0xB196B286,0xBAB4,0x101A,{0xB6,0x9C,0x00,0xAA,0x00,0x34,0x1D,0x07}};
const IID IID_IProvideClassInfo2_ = {0x25F711BE,0x2E07,0x4E84,{0x97,0xF2,0x14,0x3E,0x55,0x82,0x9B,0x5C}};


// ============================================================
// DllCanUnloadNow
// ============================================================

HRESULT vb6_DllCanUnloadNow(void) {
    if (g_vb6_cRef == 0 && g_vb6_cServerLock == 0) {
        return S_OK;
    }
    return S_FALSE;
}


// ============================================================
// Registry helpers
// ============================================================

HRESULT vb6_RegisterCoClass(const vb6_CoClassDesc* desc, const wchar_t* dllPath) {
    if (!desc || !dllPath) return E_POINTER;
    
    // String CLSID -> GUID
    CLSID clsid;
    HRESULT hr = vb6_CLSIDFromStrA((LPCSTR)desc->clsidStr, &clsid);
    if (FAILED(hr)) return hr;
    
    // Build registry key path from CLSID
    wchar_t clsidStr[64];
    StringFromGUID2(&clsid, clsidStr, 64);
    
    wchar_t keyPath[512];
    HKEY hKey;
    LONG ret;
    
    // 1. CLSID\{xxxxxxxx-...}
    swprintf(keyPath, 512, L"CLSID\\%s", clsidStr);
    ret = RegCreateKeyExW(HKEY_CLASSES_ROOT, keyPath, 0, NULL, 0, KEY_WRITE, NULL, &hKey, NULL);
    if (ret != ERROR_SUCCESS) return E_FAIL;
    // Default value = ProgID
    if (desc->progId) {
        wchar_t progIdW[256];
        MultiByteToWideChar(CP_ACP, 0, desc->progId, -1, progIdW, 256);
        RegSetValueExW(hKey, NULL, 0, REG_SZ, (BYTE*)progIdW, (DWORD)(wcslen(progIdW)+1)*2);
        // ProgID 值: ProgIDFromCLSID 唯一认这一项。C3 导入外部 ActiveX DLL 时靠它反查
        // 真实 ProgID, 缺了这一项就只能退化成按类型库名拼, 两者不一致时客户端生成的
        // New 会拿到查不到的 ProgID → 运行期 429。
        RegSetValueExW(hKey, L"ProgID", 0, REG_SZ, (BYTE*)progIdW, (DWORD)(wcslen(progIdW)+1)*2);
    }
    RegCloseKey(hKey);
    
    // 2. CLSID\{...}\InprocServer32
    swprintf(keyPath, 512, L"CLSID\\%s\\InprocServer32", clsidStr);
    ret = RegCreateKeyExW(HKEY_CLASSES_ROOT, keyPath, 0, NULL, 0, KEY_WRITE, NULL, &hKey, NULL);
    if (ret != ERROR_SUCCESS) return E_FAIL;
    RegSetValueExW(hKey, NULL, 0, REG_SZ, (BYTE*)dllPath, (DWORD)(wcslen(dllPath)+1)*2);
    // ThreadingModel = Apartment
    const wchar_t* threading = L"Apartment";
    RegSetValueExW(hKey, L"ThreadingModel", 0, REG_SZ, (BYTE*)threading, (DWORD)(wcslen(threading)+1)*2);
    RegCloseKey(hKey);
    
    // 3. ProgID registration
    if (desc->progId) {
        wchar_t progIdW[256];
        MultiByteToWideChar(CP_ACP, 0, desc->progId, -1, progIdW, 256);
        
        // ProgID key
        ret = RegCreateKeyExW(HKEY_CLASSES_ROOT, progIdW, 0, NULL, 0, KEY_WRITE, NULL, &hKey, NULL);
        if (ret != ERROR_SUCCESS) return E_FAIL;
        RegSetValueExW(hKey, NULL, 0, REG_SZ, (BYTE*)clsidStr, (DWORD)(wcslen(clsidStr)+1)*2);
        RegCloseKey(hKey);
        
        // ProgID\CLSID
        swprintf(keyPath, 512, L"%s\\CLSID", progIdW);
        ret = RegCreateKeyExW(HKEY_CLASSES_ROOT, keyPath, 0, NULL, 0, KEY_WRITE, NULL, &hKey, NULL);
        if (ret != ERROR_SUCCESS) return E_FAIL;
        RegSetValueExW(hKey, NULL, 0, REG_SZ, (BYTE*)clsidStr, (DWORD)(wcslen(clsidStr)+1)*2);
        RegCloseKey(hKey);
    }
    
    return S_OK;
}

HRESULT vb6_UnregisterCoClass(const vb6_CoClassDesc* desc) {
    if (!desc) return E_POINTER;
    
    CLSID clsid;
    HRESULT hr = vb6_CLSIDFromStrA((LPCSTR)desc->clsidStr, &clsid);
    if (FAILED(hr)) return hr;
    
    wchar_t clsidStr[64];
    StringFromGUID2(&clsid, clsidStr, 64);
    
    wchar_t keyPath[512];
    
    // Delete CLSID subkeys
    swprintf(keyPath, 512, L"CLSID\\%s\\InprocServer32", clsidStr);
    RegDeleteTreeW(HKEY_CLASSES_ROOT, keyPath);
    swprintf(keyPath, 512, L"CLSID\\%s", clsidStr);
    RegDeleteTreeW(HKEY_CLASSES_ROOT, keyPath);
    
    // Delete ProgID
    if (desc->progId) {
        wchar_t progIdW[256];
        MultiByteToWideChar(CP_ACP, 0, desc->progId, -1, progIdW, 256);
        swprintf(keyPath, 512, L"%s\\CLSID", progIdW);
        RegDeleteTreeW(HKEY_CLASSES_ROOT, keyPath);
        RegDeleteTreeW(HKEY_CLASSES_ROOT, progIdW);
    }
    
    return S_OK;
}

HRESULT vb6_GetDllPath(wchar_t* path, DWORD size) {
    HMODULE hModule = NULL;
    if (!GetModuleHandleExW(GET_MODULE_HANDLE_EX_FLAG_FROM_ADDRESS, (LPCWSTR)&vb6_GetDllPath, &hModule)) {
        return E_FAIL;
    }
    DWORD len = GetModuleFileNameW(hModule, path, size);
    if (len == 0 || len >= size) return E_FAIL;
    return S_OK;
}


// ============================================================
// TypeLib registration helpers
// ============================================================

HRESULT vb6_RegisterTypeLib(const wchar_t* dllPath) {
    if (!dllPath) return E_POINTER;
    
    // Load TypeLib from DLL resource (resource type=TYPELIB, ID=1)
    ITypeLib* pTypeLib = NULL;
    HRESULT hr = LoadTypeLib(dllPath, &pTypeLib);
    if (FAILED(hr)) {
        // TypeLib resource may not exist, not a fatal error
        return S_FALSE;
    }
    
    // Register TypeLib in registry
    hr = RegisterTypeLib(pTypeLib, (OLECHAR*)dllPath, NULL);
    if (SUCCEEDED(hr)) {
        // Add TypeLib subkey to each coclass CLSID entry
        // RegisterTypeLib may not add this if the CLSID entry already exists
        TLIBATTR* pAttr = NULL;
        hr = pTypeLib->lpVtbl->GetLibAttr(pTypeLib, &pAttr);
        if (SUCCEEDED(hr) && pAttr) {
            UINT typeCount = pTypeLib->lpVtbl->GetTypeInfoCount(pTypeLib);
            for (UINT i = 0; i < typeCount; i++) {
                TYPEKIND tk;
                pTypeLib->lpVtbl->GetTypeInfoType(pTypeLib, i, &tk);
                if (tk == TKIND_COCLASS) {
                    ITypeInfo* pInfo = NULL;
                    if (SUCCEEDED(pTypeLib->lpVtbl->GetTypeInfo(pTypeLib, i, &pInfo))) {
                        TYPEATTR* pTA = NULL;
                        if (SUCCEEDED(pInfo->lpVtbl->GetTypeAttr(pInfo, &pTA))) {
                            // Add CLSID\{clsid}\TypeLib = {LibID}
                            wchar_t clsidStr[64];
                            StringFromGUID2(&pTA->guid, clsidStr, 64);
                            wchar_t libidStr[64];
                            StringFromGUID2(&pAttr->guid, libidStr, 64);
                            wchar_t keyPath[512];
                            HKEY hKey;
                            swprintf(keyPath, 512, L"CLSID\\%s\\TypeLib", clsidStr);
                            if (RegCreateKeyExW(HKEY_CLASSES_ROOT, keyPath, 0, NULL, 0, KEY_WRITE, NULL, &hKey, NULL) == ERROR_SUCCESS) {
                                RegSetValueExW(hKey, NULL, 0, REG_SZ, (BYTE*)libidStr, (DWORD)(wcslen(libidStr)+1)*2);
                                RegCloseKey(hKey);
                            }
                            pInfo->lpVtbl->ReleaseTypeAttr(pInfo, pTA);
                        }
                        pInfo->lpVtbl->Release(pInfo);
                    }
                }
            }
            pTypeLib->lpVtbl->ReleaseTLibAttr(pTypeLib, pAttr);
        }
    }
    ITypeLib_Release(pTypeLib);
    return hr;
}

HRESULT vb6_UnregisterTypeLib(const wchar_t* dllPath) {
    if (!dllPath) return E_POINTER;
    
    // Load TypeLib first to get LibID and version
    ITypeLib* pTypeLib = NULL;
    HRESULT hr = LoadTypeLib(dllPath, &pTypeLib);
    if (FAILED(hr)) return S_FALSE;
    
    TLIBATTR* pAttr = NULL;
    hr = pTypeLib->lpVtbl->GetLibAttr(pTypeLib, &pAttr);
    if (SUCCEEDED(hr) && pAttr) {
        // ai/022 B17: 这一行的实参顺序原先就错了 —— UnRegisterTypeLib 的原型是
        // (libID, wVerMajor, wVerMinor, **lcid**, **syskind**), 旧写法把 syskind 塞进了 lcid
        // 槽 (SYS_WIN64=3)、把 lcid 塞进了 syskind 槽, 于是两个键都找错 → 函数失败、而本函数
        // 一律返回 S_OK ⇒ **每次反注册都静默漏掉整棵 TypeLib 键** (实测: 注册后 CLSID/ProgID
        // 都清干净了, `TypeLib\{libid}` 还在)。顺序改正后按报出的 lcid/syskind 反注册。
        // lcid 兜底 0x0409: 我们的库是中性的 (头里 lcid=0), RegisterTypeLib 记在 409 下。
        DWORD lcid = pAttr->lcid ? pAttr->lcid : 0x0409;
        SYSKIND syskind = pAttr->syskind ? pAttr->syskind : SYS_WIN64;
        UnRegisterTypeLib(&pAttr->guid, pAttr->wMajorVerNum, pAttr->wMinorVerNum,
                         lcid, syskind);
        pTypeLib->lpVtbl->ReleaseTLibAttr(pTypeLib, pAttr);
    }
    ITypeLib_Release(pTypeLib);
    
    return S_OK;
}
